"""
parameter.py

Hyperparameters for the visual transformer.

Author: Atharva Gupta
Date Created: 17-10-2023
"""

IMAGE_SIZE = 128
PATCH_SIZE = 8
BATCH_SIZE = 32
PROJECTION_DIM = 512 
LEARNING_RATE = 0.0005
NUM_HEADS = 5  
DROPOUT_RATE = 0.2
NUM_LAYERS = 5  
WEIGHT_DECAY = 0.0001
EPOCHS = 10
MLP_HEAD_UNITS = [256, 128]
DATA_LOAD_PATH = "AD_NC"
MODEL_SAVE_PATH = "PATTERNANALYSIS/vision_transformer"

INPUT_SHAPE = (3, IMAGE_SIZE, IMAGE_SIZE)  
HIDDEN_UNITS = [PROJECTION_DIM * 2, PROJECTION_DIM]
NUM_PATCHES = (IMAGE_SIZE // PATCH_SIZE) ** 2